### ISSUE TITLE
url save error

### ISSUE THREAD

**Issue by b3z** [b3z/reventlou#6]
```sh
[2020-12-15T13:04:57.662] [ERROR] [IMS] - ReplyError: Syntax error at offset 5 near https
    at parseError (/Users/luca/git/reventlou/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/luca/git/reventlou/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'FT.SEARCH',
  args: [ 'index', 'https://google.com' ]
}
(node:19532) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at IpcMainImpl.<anonymous> (/Users/luca/git/reventlou/dist/index.js:266:41)
    at step (/Users/luca/git/reventlou/dist/index.js:33:23)
    at Object.next (/Users/luca/git/reventlou/dist/index.js:14:53)
    at fulfilled (/Users/luca/git/reventlou/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
```

**Comment by b3z** [comment]
So the issue is that ':' is used for tags (?!) and that's the reason why we get an error. Right now I don't find any information on how to escape that or how to deal with that. #redis on freenode couldn't help me out and the docs don't do so either.

Atm its possible to save urls containing this char, you can also search for them but it will be just a search on the words in the url and not the chars. Anyway I guess that's fine and does the job.

If there is a better solution coming up I would be happy.
